//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clen
    {
        public Clen()
        {
            this.DruzstvaCleni = new HashSet<DruzstvaCleni>();
            this.Druzstva = new HashSet<Druzstvo>();
            this.Turnajes = new HashSet<Turnaj>();
            this.UserCleni = new HashSet<UserClen>();
            this.CleniInRoles = new HashSet<CleniInRole>();
        }
    
        public int ClenId { get; set; }
        public string Jmeno { get; set; }
        public string Prijmeni { get; set; }
        public string TitulPred { get; set; }
        public string TitulZa { get; set; }
        public bool JeClen { get; set; }
        public string RodneCislo { get; set; }
        public Nullable<System.DateTime> DatumNarozeni { get; set; }
        public Nullable<int> PohlaviId { get; set; }
        public Nullable<int> Vek { get; set; }
        public string PohlavyNazev { get; set; }
        public string Fotka { get; set; }
    
        public virtual Adresa Adresa { get; set; }
        public virtual Kontakt Kontakt { get; set; }
        public virtual Registrace Registrace { get; set; }
        public virtual Rozhodci Rozhodci { get; set; }
        public virtual Trener Trener { get; set; }
        public virtual ICollection<DruzstvaCleni> DruzstvaCleni { get; set; }
        public virtual ICollection<Druzstvo> Druzstva { get; set; }
        public virtual ICollection<Turnaj> Turnajes { get; set; }
        public virtual ICollection<UserClen> UserCleni { get; set; }
        public virtual ICollection<CleniInRole> CleniInRoles { get; set; }
    }
}
