//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public Disciplina()
        {
            this.Souteze = new HashSet<Soutez>();
            this.Rekordy = new HashSet<Rekord>();
        }
    
        public int DisciplinaId { get; set; }
        public int PocetHodu { get; set; }
        public int DisciplinyKategorieId { get; set; }
        public string Popis { get; set; }
    
        public virtual ICollection<Soutez> Souteze { get; set; }
        public virtual DisciplinyKategorie DisciplinyKategorie { get; set; }
        public virtual ICollection<Rekord> Rekordy { get; set; }
    }
}
