//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Druzstvo
    {
        public Druzstvo()
        {
            this.DruzstvoCleni = new HashSet<DruzstvaCleni>();
        }
    
        public int DruzstvoId { get; set; }
        public string Nazev { get; set; }
        public string Pismeno { get; set; }
        public int SoutezId { get; set; }
        public bool Existuje { get; set; }
        public int VedouciId { get; set; }
        public int TrenerId { get; set; }
        public string Popis { get; set; }
    
        public virtual Clen Vedouci { get; set; }
        public virtual Soutez Soutez { get; set; }
        public virtual Trener Trener { get; set; }
        public virtual ICollection<DruzstvaCleni> DruzstvoCleni { get; set; }
    }
}
