//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DruzstvaCleni
    {
        public int DruzstvoClenId { get; set; }
        public int DruzstvoId { get; set; }
        public int ClenId { get; set; }
    
        public virtual Clen Clen { get; set; }
        public virtual Druzstvo Druzstvo { get; set; }
    }
}
