//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klub
    {
        public int KlubId { get; set; }
        public string Nazev { get; set; }
        public string IC { get; set; }
        public string CisloUctu { get; set; }
        public string Mail { get; set; }
        public string WWW { get; set; }
        public int KodKlubu { get; set; }
        public string Image { get; set; }
        public int WebPageId { get; set; }
    
        public virtual WebPage WebPage { get; set; }
    }
}
