//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KuzelnaProgramSluzba
    {
        public int KuzelnaProgramSluzbaId { get; set; }
        public int KuzelnaProgramId { get; set; }
        public int ClenId { get; set; }
        public Nullable<System.DateTime> SluzbaDatumCasOd { get; set; }
        public Nullable<System.DateTime> SluzbaDatumCasDo { get; set; }
    
        public virtual Clen Clen { get; set; }
        public virtual KuzelnaProgram KuzelnaProgram { get; set; }
    }
}
