//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kuzelna
    {
        public int KuzelnaId { get; set; }
        public string Ulice { get; set; }
        public int CisloPopisne { get; set; }
        public string Obec { get; set; }
        public int Psc { get; set; }
        public string Popis { get; set; }
        public string GPS { get; set; }
        public Nullable<System.DateTime> KoladacePlatnaDo { get; set; }
    }
}
