//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KuzelnaProgram
    {
        public KuzelnaProgram()
        {
            this.KuzelnaProgramSluzby = new HashSet<KuzelnaProgramSluzba>();
        }
    
        public int KuzelnaProgramId { get; set; }
        public string ProgramNazev { get; set; }
        public System.DateTime ProgramDatumCasOd { get; set; }
        public System.DateTime ProgramDatumCasDo { get; set; }
        public string Poznamka { get; set; }
        public bool OpakovatKazdyTyden { get; set; }
        public Nullable<System.DateTime> OpakovatDatumDo { get; set; }
        public bool JeAktivni { get; set; }
        public int ProgramKategorieId { get; set; }
    
        public virtual ICollection<KuzelnaProgramSluzba> KuzelnaProgramSluzby { get; set; }
        public virtual KuzelnaProgramKategorie KuzelnaProgramKategorie { get; set; }
    }
}
