//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        public int MainMenuId { get; set; }
        public string Text { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public int MenuLevelId { get; set; }
        public int OrderId { get; set; }
        public int WebPageId { get; set; }
    
        public virtual WebPage WebPage { get; set; }
    }
}
