//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekord
    {
        public int RekordId { get; set; }
        public string Nazev { get; set; }
        public int DisciplinaId { get; set; }
        public int PocetHracu { get; set; }
        public int RekordyKategorieId { get; set; }
        public bool JeRegistrovan { get; set; }
        public int Nahoz { get; set; }
        public System.DateTime DatumNahozu { get; set; }
        public string Popis { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual RekordyKategorie RekordyKategorie { get; set; }
    }
}
