//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soutez
    {
        public Soutez()
        {
            this.Druzstva = new HashSet<Druzstvo>();
            this.Vysledky = new HashSet<Vysledek>();
            this.Zapasy = new HashSet<Zapas>();
        }
    
        public int SoutezId { get; set; }
        public string Nazev { get; set; }
        public int KategorieSoutezeId { get; set; }
        public int PocetNutnychDrah { get; set; }
        public int MinPocetHracu { get; set; }
        public int DisciplinaId { get; set; }
    
        public virtual KategorieSouteze KategorieSouteze { get; set; }
        public virtual ICollection<Druzstvo> Druzstva { get; set; }
        public virtual ICollection<Vysledek> Vysledky { get; set; }
        public virtual Disciplina Discipliny { get; set; }
        public virtual ICollection<Zapas> Zapasy { get; set; }
    }
}
