//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VysledkyKola
    {
        public int VysledkyKoloId { get; set; }
        public int VysledekId { get; set; }
        public int PorCisloKola { get; set; }
        public string Zpravodaj { get; set; }
    
        public virtual Vysledek Vysledek { get; set; }
    }
}
