//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vysledek
    {
        public Vysledek()
        {
            this.VysledkyKol = new HashSet<VysledkyKola>();
        }
    
        public int VysledekId { get; set; }
        public int RocnikId { get; set; }
        public int SoutezId { get; set; }
        public string Tabulka { get; set; }
        public int WebPageIId { get; set; }
        public string Rozpis { get; set; }
        public string Rozlosovani { get; set; }
        public string SoupiskaPodzim { get; set; }
        public string SoupiskaJaro { get; set; }
    
        public virtual Rocnik Rocnik { get; set; }
        public virtual Soutez Soutez { get; set; }
        public virtual ICollection<VysledkyKola> VysledkyKol { get; set; }
        public virtual WebPage WebPage { get; set; }
    }
}
