//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPage
    {
        public WebPage()
        {
            this.MainMenus = new HashSet<MainMenu>();
            this.Druzstva = new HashSet<Druzstvo>();
            this.Turnaje = new HashSet<Turnaj>();
            this.Kuzelnas = new HashSet<Kuzelna>();
            this.Klubies = new HashSet<Klub>();
        }
    
        public int WebPageId { get; set; }
        public string HtmlText { get; set; }
        public string Nazev { get; set; }
    
        public virtual ICollection<MainMenu> MainMenus { get; set; }
        public virtual ICollection<Druzstvo> Druzstva { get; set; }
        public virtual ICollection<Turnaj> Turnaje { get; set; }
        public virtual ICollection<Kuzelna> Kuzelnas { get; set; }
        public virtual ICollection<Klub> Klubies { get; set; }
    }
}
