//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlavojMVC4_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapas
    {
        public int ZapasId { get; set; }
        public int SoutezId { get; set; }
        public string KuzelnaNazev { get; set; }
        public bool KuzelnaDomaci { get; set; }
        public System.DateTime ZapasDatumCasOd { get; set; }
        public System.DateTime ZapasDatumCasDo { get; set; }
        public string Druzstvo1Nazev { get; set; }
        public string Druzstvo2Nazev { get; set; }
        public Nullable<System.DateTime> SrazDatumCas { get; set; }
        public string MistoSrazu { get; set; }
        public string Poznamka { get; set; }
        public int RozhodciId { get; set; }
    
        public virtual Rozhodci Rozhodci { get; set; }
        public virtual Soutez Soutez { get; set; }
    }
}
